// Code generated by sqlc. DO NOT EDIT.
// source: pages.sql

package db

import (
	"context"
)

const createPage = `-- name: CreatePage :one
INSERT INTO pages(title,slug,body)values($1,$2,$3) RETURNING id, parent_id, title, slug, body, create_at
`

type CreatePageParams struct {
	Title string
	Slug  string
	Body  string
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.queryRow(ctx, q.createPageStmt, createPage, arg.Title, arg.Slug, arg.Body)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Title,
		&i.Slug,
		&i.Body,
		&i.CreateAt,
	)
	return i, err
}
